// Code generated by protoc-gen-go. DO NOT EDIT.
// source: egm.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransferFunds struct {
	CashableMoneyInCents      uint64   `protobuf:"varint,1,opt,name=cashableMoneyInCents,proto3" json:"cashableMoneyInCents,omitempty"`
	RestrictedMoneyInCents    uint64   `protobuf:"varint,2,opt,name=restrictedMoneyInCents,proto3" json:"restrictedMoneyInCents,omitempty"`
	NonRestrictedMoneyInCents uint64   `protobuf:"varint,3,opt,name=nonRestrictedMoneyInCents,proto3" json:"nonRestrictedMoneyInCents,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *TransferFunds) Reset()         { *m = TransferFunds{} }
func (m *TransferFunds) String() string { return proto.CompactTextString(m) }
func (*TransferFunds) ProtoMessage()    {}
func (*TransferFunds) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8258e386ee6ba86, []int{0}
}

func (m *TransferFunds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferFunds.Unmarshal(m, b)
}
func (m *TransferFunds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferFunds.Marshal(b, m, deterministic)
}
func (m *TransferFunds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferFunds.Merge(m, src)
}
func (m *TransferFunds) XXX_Size() int {
	return xxx_messageInfo_TransferFunds.Size(m)
}
func (m *TransferFunds) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferFunds.DiscardUnknown(m)
}

var xxx_messageInfo_TransferFunds proto.InternalMessageInfo

func (m *TransferFunds) GetCashableMoneyInCents() uint64 {
	if m != nil {
		return m.CashableMoneyInCents
	}
	return 0
}

func (m *TransferFunds) GetRestrictedMoneyInCents() uint64 {
	if m != nil {
		return m.RestrictedMoneyInCents
	}
	return 0
}

func (m *TransferFunds) GetNonRestrictedMoneyInCents() uint64 {
	if m != nil {
		return m.NonRestrictedMoneyInCents
	}
	return 0
}

type CommonResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8258e386ee6ba86, []int{1}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type JXRequest struct {
	DispenseType         string   `protobuf:"bytes,1,opt,name=dispenseType,proto3" json:"dispenseType,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JXRequest) Reset()         { *m = JXRequest{} }
func (m *JXRequest) String() string { return proto.CompactTextString(m) }
func (*JXRequest) ProtoMessage()    {}
func (*JXRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8258e386ee6ba86, []int{2}
}

func (m *JXRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JXRequest.Unmarshal(m, b)
}
func (m *JXRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JXRequest.Marshal(b, m, deterministic)
}
func (m *JXRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JXRequest.Merge(m, src)
}
func (m *JXRequest) XXX_Size() int {
	return xxx_messageInfo_JXRequest.Size(m)
}
func (m *JXRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JXRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JXRequest proto.InternalMessageInfo

func (m *JXRequest) GetDispenseType() string {
	if m != nil {
		return m.DispenseType
	}
	return ""
}

func (m *JXRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8258e386ee6ba86, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TransferFunds)(nil), "proto.TransferFunds")
	proto.RegisterType((*CommonResponse)(nil), "proto.CommonResponse")
	proto.RegisterType((*JXRequest)(nil), "proto.JXRequest")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("egm.proto", fileDescriptor_f8258e386ee6ba86) }

var fileDescriptor_f8258e386ee6ba86 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x69, 0xff, 0x6d, 0xfe, 0xcd, 0x50, 0x45, 0x86, 0x5a, 0xb4, 0x27, 0xc9, 0xc9, 0x83,
	0x16, 0x6d, 0xc1, 0x93, 0xb7, 0x1a, 0x8b, 0xc5, 0x5e, 0x42, 0x0b, 0x5e, 0xb7, 0xcd, 0xa8, 0x01,
	0x33, 0xbb, 0xee, 0x6e, 0xc0, 0xdc, 0xfd, 0x52, 0x7e, 0x3b, 0xe9, 0xba, 0x16, 0x22, 0x0d, 0xe8,
	0x29, 0x79, 0xf3, 0xde, 0x8f, 0x9d, 0x7d, 0x0b, 0x21, 0x3d, 0xe5, 0x43, 0xa5, 0xa5, 0x95, 0xd8,
	0x76, 0x9f, 0xe8, 0xa3, 0x01, 0x7b, 0x0b, 0x2d, 0xd8, 0x3c, 0x92, 0xbe, 0x2d, 0x38, 0x35, 0x38,
	0x82, 0xde, 0x5a, 0x98, 0x67, 0xb1, 0x7a, 0xa1, 0xb9, 0x64, 0x2a, 0xef, 0x78, 0x42, 0x6c, 0xcd,
	0x51, 0xe3, 0xa4, 0x71, 0xda, 0x4a, 0x76, 0x7a, 0x78, 0x05, 0x7d, 0x4d, 0xc6, 0xea, 0x6c, 0x6d,
	0x29, 0xad, 0x50, 0x4d, 0x47, 0xd5, 0xb8, 0x78, 0x0d, 0xc7, 0x2c, 0x39, 0xd9, 0x8d, 0xfe, 0x73,
	0x68, 0x7d, 0x20, 0x3a, 0x83, 0xfd, 0x89, 0xcc, 0x73, 0xe7, 0x2b, 0xc9, 0x86, 0x70, 0x00, 0x1d,
	0xed, 0xff, 0xdd, 0xbe, 0x61, 0xb2, 0xd5, 0xd1, 0x14, 0xc2, 0xd9, 0x43, 0x42, 0xaf, 0x05, 0x19,
	0x8b, 0x11, 0x74, 0xd3, 0xcc, 0x28, 0x62, 0x43, 0x8b, 0x52, 0x7d, 0x87, 0x2b, 0x33, 0xec, 0x43,
	0x20, 0x72, 0x59, 0xb0, 0xf5, 0x97, 0xf0, 0x2a, 0xfa, 0x0f, 0xed, 0x38, 0x57, 0xb6, 0x1c, 0xbd,
	0x37, 0xa1, 0xb5, 0xe9, 0x0c, 0x2f, 0x01, 0x6e, 0x32, 0xb3, 0x69, 0x25, 0x9e, 0xce, 0xb1, 0xfb,
	0xd5, 0xf0, 0xd0, 0x85, 0x06, 0x87, 0x5e, 0xfd, 0xd8, 0xf4, 0x02, 0xc2, 0x98, 0xff, 0x44, 0x8c,
	0xa1, 0x75, 0x2f, 0x45, 0x8a, 0x3d, 0x6f, 0x57, 0x5e, 0xad, 0x0e, 0x3a, 0x87, 0x60, 0xc9, 0x0e,
	0xfb, 0xe5, 0x19, 0x9d, 0xa5, 0x4a, 0x85, 0xa5, 0xd9, 0x1b, 0x1e, 0xf8, 0xc8, 0xb6, 0xb4, 0x1a,
	0x68, 0x15, 0xb8, 0xe9, 0xf8, 0x33, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x93, 0x03, 0x41, 0x5d, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FundClient is the client API for Fund service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FundClient interface {
	DisableEGM(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error)
	EnableEGM(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error)
	Load(ctx context.Context, in *TransferFunds, opts ...grpc.CallOption) (*CommonResponse, error)
	UnLoad(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error)
	UpdateJx(ctx context.Context, in *JXRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type fundClient struct {
	cc *grpc.ClientConn
}

func NewFundClient(cc *grpc.ClientConn) FundClient {
	return &fundClient{cc}
}

func (c *fundClient) DisableEGM(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/proto.Fund/DisableEGM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundClient) EnableEGM(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/proto.Fund/EnableEGM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundClient) Load(ctx context.Context, in *TransferFunds, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/proto.Fund/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundClient) UnLoad(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/proto.Fund/UnLoad", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundClient) UpdateJx(ctx context.Context, in *JXRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/proto.Fund/UpdateJx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundServer is the server API for Fund service.
type FundServer interface {
	DisableEGM(context.Context, *Empty) (*CommonResponse, error)
	EnableEGM(context.Context, *Empty) (*CommonResponse, error)
	Load(context.Context, *TransferFunds) (*CommonResponse, error)
	UnLoad(context.Context, *Empty) (*CommonResponse, error)
	UpdateJx(context.Context, *JXRequest) (*CommonResponse, error)
}

// UnimplementedFundServer can be embedded to have forward compatible implementations.
type UnimplementedFundServer struct {
}

func (*UnimplementedFundServer) DisableEGM(ctx context.Context, req *Empty) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableEGM not implemented")
}
func (*UnimplementedFundServer) EnableEGM(ctx context.Context, req *Empty) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableEGM not implemented")
}
func (*UnimplementedFundServer) Load(ctx context.Context, req *TransferFunds) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedFundServer) UnLoad(ctx context.Context, req *Empty) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnLoad not implemented")
}
func (*UnimplementedFundServer) UpdateJx(ctx context.Context, req *JXRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJx not implemented")
}

func RegisterFundServer(s *grpc.Server, srv FundServer) {
	s.RegisterService(&_Fund_serviceDesc, srv)
}

func _Fund_DisableEGM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServer).DisableEGM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fund/DisableEGM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServer).DisableEGM(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fund_EnableEGM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServer).EnableEGM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fund/EnableEGM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServer).EnableEGM(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fund_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferFunds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fund/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServer).Load(ctx, req.(*TransferFunds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fund_UnLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServer).UnLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fund/UnLoad",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServer).UnLoad(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fund_UpdateJx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JXRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServer).UpdateJx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Fund/UpdateJx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServer).UpdateJx(ctx, req.(*JXRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fund_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Fund",
	HandlerType: (*FundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisableEGM",
			Handler:    _Fund_DisableEGM_Handler,
		},
		{
			MethodName: "EnableEGM",
			Handler:    _Fund_EnableEGM_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Fund_Load_Handler,
		},
		{
			MethodName: "UnLoad",
			Handler:    _Fund_UnLoad_Handler,
		},
		{
			MethodName: "UpdateJx",
			Handler:    _Fund_UpdateJx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egm.proto",
}
